# Generated by Django 5.2.5 on 2025-08-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("location", models.CharField(blank=True, max_length=30)),
                ("capacity", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TableReservationSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_slot", models.DateTimeField()),
                ("quantity", models.PositiveBigIntegerField(default=1)),
                ("max_amount", models.PositiveBigIntegerField()),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="booking_system_app.table",
                    ),
                ),
            ],
        ),
    ]
