# Generated by Django 5.2.5 on 2025-10-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "location",
                    models.CharField(
                        choices=[("inside", "Inside"), ("outside", "Outside")],
                        max_length=10,
                    ),
                ),
                ("capacity", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TableReservationSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_slot", models.TimeField()),
                ("date", models.DateField(blank=True, null=True)),
                ("amount", models.PositiveBigIntegerField(default=1)),
                ("available", models.BooleanField(default=True)),
                ("max_amount", models.PositiveBigIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("customer_name", models.CharField(max_length=100)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="booking_system_app.table",
                    ),
                ),
            ],
            options={
                "unique_together": {("table", "time_slot")},
            },
        ),
    ]
