# Generated by Django 5.2.5 on 2025-10-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tablereservationslot",
            unique_together={("table", "time_slot", "date")},
        ),
    ]
