# Generated by Django 5.2.5 on 2025-08-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tablereservationslot",
            old_name="quantity",
            new_name="num_people",
        ),
    ]
