# Generated by Django 5.2.5 on 2025-08-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0002_rename_quantity_tablereservationslot_num_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[("inside", "Inside"), ("outside", "Outside")],
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tablereservationslot",
            unique_together={("table", "time_slot")},
        ),
    ]
