# Generated by Django 5.2.5 on 2025-08-19 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking_system_app",
            "0002_availablehour_reservation_available_hour_weekday_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="available_hour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="booking_system_app.availablehour",
            ),
        ),
    ]
