# Generated by Django 5.2.5 on 2025-08-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0003_alter_table_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tablereservationslot",
            old_name="num_people",
            new_name="amount",
        ),
    ]
