# Generated by Django 5.2.5 on 2025-08-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0004_rename_num_people_tablereservationslot_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablereservationslot",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
