# Generated by Django 5.2.5 on 2025-08-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0005_tablereservationslot_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="location",
            field=models.CharField(
                choices=[("inside", "Inside"), ("outside", "Outside")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
