# Generated by Django 5.2.5 on 2025-08-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0006_alter_table_location_alter_table_name"),
    ]

    operations = []

def create_tables(apps, schema_editor):
    Table = apps.get_model("booking_system_app", "Table")
    
    for i in range(1, 6):
        Table = apps.get_model("booking_system_app", "Table")
        
        for i in range(1, 6):
            Table.objects.get_or_create(
                name=f"Table {i}",
                location="inside",
                defaults={"capacity":5},
            )
        for i in range(6, 11):
            Table.objects.get_or_create(
                name=f"Table {i}",
                location="outside",
                defaults={"capacity":5},
            )
def delete_tables(apps, schema_editor):
    Table = apps.get_model("booking_system_app", "Table")
    Table.objects.filter(name__startswith="Table").delete()

class Migration(migrations.Migration):
    
    dependencies = [
        ("booking_system_app", "0006_alter_table_location_alter_table_name"), 
    ]
    
    operations = [
        migrations.RunPython(create_tables, delete_tables)
    ]
    