# Generated by Django 5.2.5 on 2025-08-26 22:09

from django.db import migrations
from datetime import datetime, timedelta

class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0007_auto_20250826_2139"),
    ]

def create_dummy_slot(apps, schema_editor):
    Table = apps.get_model("booking_system_app", "Table")
    Slot = apps.get_model("booking_system_app", "TableReservationSlot")

    table = Table.objects.first()
    if table:  # only create if a table exists
        Slot.objects.get_or_create(
            pk=1,  # enforce pk=1
            defaults={
                "table": table,
                "time_slot": datetime.now() + timedelta(hours=1),
                "amount": 1,
                "max_amount": 5,
                "notes": "Dummy placeholder slot",
            }
        )

def delete_dummy_slot(apps, schema_editor):
    Slot = apps.get_model("booking_system_app", "TableReservationSlot")
    Slot.objects.filter(pk=1, notes="Dummy placeholder slot").delete()

class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0007_create_tables"),  # depends on the tables being created
    ]

    operations = [
        migrations.RunPython(create_dummy_slot, delete_dummy_slot),
    ]
