# Generated by Django 5.2.5 on 2025-08-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0008_create_dummy_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablereservationslot",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
