# Generated by Django 5.2.5 on 2025-08-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0009_tablereservationslot_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablereservationslot",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tablereservationslot",
            name="max_amount",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
