# Generated by Django 5.2.5 on 2025-08-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0010_tablereservationslot_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tablereservationslot",
            name="name",
        ),
    ]
