# Generated by Django 5.2.5 on 2025-08-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0011_remove_tablereservationslot_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablereservationslot",
            name="customer_name",
            field=models.CharField(default="Guest", max_length=100),
            preserve_default=False,
        ),
    ]
