# Generated by Django 5.2.5 on 2025-10-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0012_tablereservationslot_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablereservationslot",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
