# Generated by Django 5.2.5 on 2025-10-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system_app", "0013_tablereservationslot_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablereservationslot",
            name="time_slot",
            field=models.TimeField(),
        ),
    ]
